name = "Aglaus"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_aglaus/blob/master/LICENSE.md"
homepage = "https://github.com/dim0627/hugo_theme_aglaus"
min_version = 0.16

[author]
  name = "Daisuke Tsuji"
  homepage = "https://yet.unresolved.xyz/"

